// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Network struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Token       *Token `json:"token"`
}

type NewNetwork struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	TokenAddress string `json:"tokenAddress"`
}

type NewToken struct {
	Address     string `json:"address"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Token struct {
	Address     string     `json:"address"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Networks    []*Network `json:"networks"`
}
